Limit request size to under 10 MB for AppendRows API
lquerel/gcp-bigquery-client pull request #114
Opened 2024-12-04 11:31 UTC by imor

There's a 10 MB limit on the request size in BigQuery as documented on [this page](https://cloud.google.com/bigquery/quotas) (search `maximum request size`). If the request size goes over this limit, the `AppendRows` API returns an `INVALID_ARGUMENT` error. This PR limits the serialized rows size to 9 MB and leaves around 1 MB for the other parts of the request (this can probably also be made configurable). But more importantly, the `append_rows` function now accepts a `Rows` struct rather than a `&[Message]` which allows callers to create the `Rows` struct using any strategy they want (e.g. repeatedly halving  the `Rows` size while the API continues to return `INVALID_ARGUMENT`). This API design is better than the existing one in which the `append_rows` created the `Rows` struct from `&[Message]` slice, which left no control in callers' hands. This unfortunately breaks backward compatibility but can be shipped in the next major version bump.

2025-01-09 16:16 UTC, lquerel requested changes
Sorry for the delay. Thank you for this PR.
I left few minor comments that need to be fixed and we are good to go.

2025-01-09 16:16 UTC, lquerel commented on src/storage.rs
> +    pub fn create_rows<M: Message>(
I think it would be helpful to add a comment describing how this method works. It seems that it is the caller's responsibility to verify what has actually been sent and to implement a retry mechanism in case there are leftovers (and also even if it can be obvious for most of the people that these leftovers are at the end).

2025-01-09 16:16 UTC, lquerel commented on src/storage.rs
> +        let (rows, _) = StorageApi::create_rows(&table_descriptor, &[actor1, actor2]);
2 comments:
- Update this test to show how to use correctly this method (i.e. retry to flush potential leftovers).
- Add another test to check the behavior when there are leftovers.

2025-01-11 08:37 UTC, imor commented
Sorry this languished in draft state for quite some time. I've addressed review comments and marked it ready for review.

2025-01-11 08:40 UTC, imor commented on src/storage.rs
> +        let (rows, _) = StorageApi::create_rows(&table_descriptor, &[actor1, actor2]);
I've factored out the retrying code in a separate function and called it twice. Once in which the rows are processed in a single AppendRows call and another time when multiple AppendRows calls are needed. Hope that this will serve as an example of how to write a typical retrying logic in case not all rows are processed in the last call.

2025-01-11 08:41 UTC, imor commented on src/storage.rs
> +    pub fn create_rows<M: Message>(
Added a comment explaining in detail how the `create_rows` works. This comment together with the example code should demonstrate what typical usage of this and related functions looks like.

2025-01-12 16:34 UTC, lquerel approved these changes
LGTM. Thanks

2025-01-12 16:34 UTC, merged

2025-01-12 22:51 UTC, lquerel commented
FYI, the version 0.25.0 (including your PR) has been published on crates.io. Thanks

2025-01-13 08:51 UTC, imor commented
> FYI, the version 0.25.0 (including your PR) has been published on crates.io. Thanks

Great, thank you Laurent.