Feature/paginate through all jobs list
lquerel/gcp-bigquery-client pull request #63
Opened 2023-09-25 16:00 UTC by Shirlo

This PR adds a method to allow users to paginate through all the jobs in the jobs list. It is helpful as it allows people to obtain all of the jobs from the list jobs API.

Also, fix a bug in `JobListJobs` and `Job` struct, the API sends `user_email` in this format and not in camel case like in the struct.

2023-09-26 11:41 UTC, govrin approved these changes

2023-09-26 12:06 UTC, ItzikBH approved these changes

2023-09-26 15:35 UTC, lquerel requested changes
Thank you for this contribution. It's a great addition to this crate. I've made two requests; once they're addressed, we'll be ready to go.

2023-09-26 15:35 UTC, lquerel commented on src/job.rs
> +                yield Ok(process_resp.as_ref().expect("JobList is not present").clone());
A missing `JobList` should not be treated as a fatal error. Therefore, this `expect` should be replaced with a BQError to allow the caller to handle this error appropriately.

2023-09-26 15:35 UTC, lquerel commented on src/model/job_list_parameters.rs
> +    #[serde(skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_projection")]
Why not use an enum with two variants: full and minimal, and let Serde handle the serialization?

2023-10-01 17:26 UTC, merged

2023-10-01 20:31 UTC, lquerel commented
I made few changes to your code.
Version 0.17.1 available on crates.io